apiVersion: v1
kind: Service
metadata:
apiVersion: v1
kind: Service
metadata:
  name: endpoint
  labels:
    name: endpoint-nodeport-svc
spec:
  type: NodePort
  ports:
  - port: 5000
    nodePort: 30001
  selector:
    app: endpoint
